//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadImageCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Student
    {
        public int StudentId { get; set; }

        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Name is Required")]
        public string StudentName { get; set; }

        [DisplayName("Department")]
        [Required(ErrorMessage = "Department is Required")]
        public string Branch { get; set; }

        [DisplayName("Choose Image")]
        public string ImagePath { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
