//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetMotor
    {
        public string VehicleLookupResponseId { get; set; }
        public string Status { get; set; }
        public string RegStatus { get; set; }
        public string Message { get; set; }
        public string RegistrationNo { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string ChasisNo { get; set; }
        public string EngineNo { get; set; }
        public string vehicleClass { get; set; }
        public string FuelType { get; set; }
        public string Maker { get; set; }
        public string Rto { get; set; }
        public string UniqueId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedOn { get; set; }
        public string VLookUpResponseObject { get; set; }
        public Nullable<long> LeadId { get; set; }
        public string GVW { get; set; }
        public string insurance_expired { get; set; }
        public string insurance_policy_no { get; set; }
        public string insurance_upto { get; set; }
        public string commercial_flag { get; set; }
        public string fla_cubic_cap { get; set; }
        public string FLA_Seat_Capacity { get; set; }
        public string Insurance_Company { get; set; }
    }
}
