//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Image.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Information
    {
        public int ID { get; set; }

        [DisplayName("Student Name")]
        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }
        [DisplayName("Student Class")]
        [Required(ErrorMessage = "Standerd is Required")]
        public string Standerd { get; set; }
        [DisplayName("Choose Image")]
        public string Image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
